### ISSUE TITLE
Add support for injectConfigsInLuaScript

### ISSUE THREAD

**Issue by Frotty** [inwc3/wc3libs#43]
Analogous to `injectConfigsInJassScript`.

**Comment by WaterKnight** [comment]
Not sure yet how to implement this. Lua gives you more flexibility, The main and other functions may not be known at compile time. Moreover, you can have instructions in the outer scope of the chunk, so that may even come before the invocation of config/main. I think the native calls should be erased, those from map info are only useful in config/main anyway. Then, you append and thereby overwrite the config/main while still calling the previous implementations. Maybe it would still be better to only provide the generation obtained from w3i and give the context the responsibility of linking it to the existing war3map.lua rather than trying some intermingled injection.

**Comment by Frotty** [comment]
How does the world editor do?
I think WE and Wurst ways are the most important to be supported, rest not so much.

**Comment by WaterKnight** [comment]
The WE does not inject it all. It recreates the script on save. But I have taken a look at the other implementation. The main function does not contain the player information, only sound environment, day/night models, camera bounds and something like that. I have not touched the main. And the config itself should normally only contain very special native calls. As it completely removes the previous config function, the sound in lobby injection is not supported for instance at the moment.

**Comment by Frotty** [comment]
> The WE does not inject at all. It recreates the script on save.

Duh. I ment how the created one looks, obviously.

>  The main function does not contain the player information, only sound environment, day/night models, camera bounds and something like that.

aha? So for lua maps they load it from w3i or what? How can it be gone? What about player start positions?

**Comment by WaterKnight** [comment]
> Duh. I ment how the created one looks, obviously.

Well, that was not my concern. My concern is that there are potentially multiple tools in the build chain that try to transform the main/config, each with their own assumptions. The current implementation completely discards the previous config function, so if you had already placed something therein different from what the WE does, it is lost. You could also add the sound environment, day/night models, camera bounds from w3i to the main function analogous to the WE but main contains even more stuff. Discarding its previous version would be fatal.

> aha? So for lua maps they load it from w3i or what? How can it be gone? What about player start positions?

No, the player information is in config.

**Comment by Frotty** [comment]
> edit: So for clarification: Will ship some solution by next weekend. For the common use cases, there is no problem.

Nice 🍻 👍

**Comment by ManfredHamlescher** [comment]
Whom are you ppl? How can I get in touch with you?

**Comment by Frotty** [comment]
A bunch of modders :)
Join here https://kiwiirc.com/nextclient/#irc://irc.quakenet.org/#inwc.de-maps

**Comment by ManfredHamlescher** [comment]
kay I'm there

**Comment by WaterKnight** [comment]
Has this been resolved in 05b660fd002082f47ff711651df5201c65171b83?

**Comment by Frotty** [comment]
Yes
