### ISSUE TITLE
how can get objId by field in AbilityMetaData.slk?

### ISSUE THREAD

**Issue by qq1053831109** [inwc3/wc3libs#66]
how can get objId by field in AbilityMetaData.slk?

**Comment by WaterKnight** [comment]
You mean https://github.com/inwc3/wc3libs/blob/63e9d69615bde1247480820e516f4ee7762ff6b2/src/main/java/net/moonlightflower/wc3libs/slk/app/meta/CommonMetaSLK.java#L36? Well you can iterate over all objects in the SLK and see if its 'field' value matches the one you seek for. This 'field' property is the name used in the game SLKs, is it not? Which might not be bijective, like multiple meta objects map to the same Data field names (together with index).

**Comment by qq1053831109** [comment]
many objid map to data field ! so how i choese one objid?

**Comment by WaterKnight** [comment]
What is your use case? What are you trying to achieve and why?

If you are trying to back-translate from game SLK to object modifications (why do you need to do that?), then you need more information. The meta SLK objects that correspond to a data field also correspond to specific ability codes. That is like for Holy Light you can configure the healed amount, while with Cluster Rockets you can configure the amount of rockets, those are different meta SLK objects but may map to the same SLK field name (DataA/B/C/... + level). There is a SLK field "abilCode" (iirc) that tells the editor and game what the functional base object is, whether it's a Holy Light or Cluster Rockets.

I have not named all the different specific meta SLK fields in the library yet, because there really is a ton of them. You can still work with the raw values, nonetheless. There should be one field in the meta SLK which says what objects it is restricted to. I reckon it was this one -> https://github.com/inwc3/wc3libs/blob/63e9d69615bde1247480820e516f4ee7762ff6b2/src/main/java/net/moonlightflower/wc3libs/slk/app/meta/CommonMetaSLK.java#L55
